# Generated by Django 2.2 on 2019-04-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='parent',
            new_name='user',
        ),
    ]
