# Generated by Django 2.2 on 2019-04-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190416_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='user',
            new_name='parent',
        ),
    ]
