# Generated by Django 2.2 on 2019-04-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190426_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='not_allowed',
            field=models.ManyToManyField(blank=True, related_name='not_alloweds', to='api.Item'),
        ),
    ]
