# Generated by Django 2.2 on 2019-04-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190416_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='school',
        ),
        migrations.AddField(
            model_name='parent',
            name='school',
            field=models.ManyToManyField(to='api.School'),
        ),
    ]
