# Generated by Django 2.2 on 2019-04-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190424_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('الصف الاول', 'الصف الاول'), ('الصف الثاني', 'الصف الثاني'), ('الصف الثالث', 'الصف الثالث'), ('الصف الرابع', 'الصف الرابع'), ('الصف الخامس', 'الصف الخامس'), ('الصف السادس', 'الصف السادس')], default=1, max_length=10),
        ),
    ]
