# Generated by Django 2.2 on 2019-04-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190419_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schoolitems', to='api.Category'),
            preserve_default=False,
        ),
    ]
