# Generated by Django 2.2 on 2019-04-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190420_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolcategories', to='api.School'),
        ),
    ]
